# -*- coding: utf-8 -*-
"""kdr2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QxR5OtLy-KefoBI0-RbHgwJQ92ImI8hr
"""

import os
import zipfile
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# 1. Unzip the file
zip_path = '/content/School_Shoes_Classification-20260426T060136Z-3-001 (1).zip' # Update this name
extract_path = '/content/dataset'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

# 2. Data Augmentation (Matching your uploaded pipeline)
datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2,
    rotation_range=15,
    brightness_range=[0.7, 1.3],
    horizontal_flip=True,
    vertical_flip=True
)

train_gen = datagen.flow_from_directory(
    os.path.join(extract_path, 'School_Shoes_Classification'), target_size=(224, 224), batch_size=32,
    class_mode='categorical', subset='training')

val_gen = datagen.flow_from_directory(
    os.path.join(extract_path, 'School_Shoes_Classification'), target_size=(224, 224), batch_size=32,
    class_mode='categorical', subset='validation')

# Store class names for later
class_names = list(train_gen.class_indices.keys())

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras import layers, models

base_mobilenet = MobileNetV2(weights='imagenet', include_top=False, input_shape=(224,224,3))
base_mobilenet.trainable = False

class_names = list(train_gen.class_indices.keys())

model_mobilenet = models.Sequential([
    base_mobilenet,
    layers.GlobalAveragePooling2D(),
    layers.Dense(len(class_names), activation='softmax')
])

model_mobilenet.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
history_mobilenet = model_mobilenet.fit(train_gen, validation_data=val_gen, epochs=15)

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

def plot_confusion_matrix(model, generator):
    # Reset generator to ensure labels and predictions align
    generator.reset()

    # Get true labels and model predictions
    y_true = generator.classes
    preds = model.predict(generator)
    y_pred = np.argmax(preds, axis=1)

    # Generate Matrix
    cm = confusion_matrix(y_true, y_pred)

    plt.figure(figsize=(10, 8))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=class_names, yticklabels=class_names)
    plt.title('MobileNetV2: Confusion Matrix (Actual vs Predicted)')
    plt.ylabel('Actual Condition')
    plt.xlabel('Predicted Condition')
    plt.show()

# Run for your model
plot_confusion_matrix(model_mobilenet, val_gen)

import pandas as pd

def plot_per_class_accuracy(model, generator):
    generator.reset()
    y_true = generator.classes
    y_pred = np.argmax(model.predict(generator), axis=1)

    # Calculate accuracy for each class
    cm = confusion_matrix(y_true, y_pred)
    class_accuracies = cm.diagonal() / cm.sum(axis=1)

    # Create Bar Chart
    plt.figure(figsize=(12, 6))
    colors = plt.cm.viridis(np.linspace(0, 1, len(class_names)))
    plt.bar(class_names, class_accuracies, color=colors)

    plt.title('MobileNetV2: Accuracy by Category')
    plt.ylabel('Accuracy Score (0 to 1.0)')
    plt.xticks(rotation=45)
    plt.ylim(0, 1.1)

    # Add labels on top of bars
    for i, v in enumerate(class_accuracies):
        plt.text(i, v + 0.02, f"{v:.2f}", ha='center', fontweight='bold')

    plt.show()

plot_per_class_accuracy(model_mobilenet, val_gen)

import numpy as np
import matplotlib.pyplot as plt # Ensure matplotlib is imported for plotting

def plot_probability_distribution(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)

    plt.figure(figsize=(12, 6))
    # Adjust slicing based on your specific classes
    plt.hist(y_pred_probs[y_true == 0][:, 1], bins=20, alpha=0.5, label='Class 0 (True Label)', color='#3498db', edgecolor='black')
    plt.hist(y_pred_probs[y_true == 1][:, 1], bins=20, alpha=0.5, label='Class 1 (True Label)', color='#e74c3c', edgecolor='black')

    plt.axvline(0.5, color='green', linestyle='--', linewidth=3, label='Decision Threshold (0.5)')
    plt.title('Prediction Probability Distribution', fontweight='bold')
    plt.xlabel('Predicted Probability', fontweight='bold')
    plt.ylabel('Frequency', fontweight='bold')
    plt.legend()
    plt.grid(axis='y', alpha=0.3)
    plt.show()

plot_probability_distribution(model_mobilenet, val_gen)

import matplotlib.pyplot as plt

def plot_history(history, model_name="MobileNetV3Small"):
    # Accuracy Plot
    plt.figure(figsize=(9, 6))
    plt.plot(history.history['accuracy'], label='Training Accuracy',
             color='#2ecc71', marker='o', linewidth=2.5, markersize=5)
    plt.plot(history.history['val_accuracy'], label='Validation Accuracy',
             color='#e74c3c', marker='s', linewidth=2.5, markersize=5)
    plt.title(f'{model_name} - Training vs Validation Accuracy', fontweight='bold')
    plt.xlabel('Epoch', fontweight='bold')
    plt.ylabel('Accuracy', fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.show()

    # Loss Plot
    plt.figure(figsize=(9, 6))
    plt.plot(history.history['loss'], label='Training Loss',
             color='#3498db', marker='o', linewidth=2.5, markersize=5)
    plt.plot(history.history['val_loss'], label='Validation Loss',
             color='#f39c12', marker='s', linewidth=2.5, markersize=5)
    plt.title(f'{model_name} - Training vs Validation Loss', fontweight='bold')
    plt.xlabel('Epoch', fontweight='bold')
    plt.ylabel('Loss', fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.show()

plot_history(history_mobilenet, "MobileNetV2")

import numpy as np
import seaborn as sns
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt # Ensure matplotlib is imported for plotting

def plot_mobilenet_error_analysis(model, generator):
    generator.reset()
    y_true = generator.classes
    y_pred_probs = model.predict(generator)
    y_pred = np.argmax(y_pred_probs, axis=1)
    errors = np.abs(y_true - y_pred_probs.max(axis=1))

    fig, axes = plt.subplots(2, 2, figsize=(16, 12))
    fig.suptitle('MobileNetV2 - Comprehensive Error Analysis', fontsize=16, fontweight='bold')

    # 1. Error Distribution
    axes[0, 0].hist(errors, bins=25, color='#e74c3c', alpha=0.7, edgecolor='black')
    axes[0, 0].set_title('Error Distribution', fontweight='bold')
    axes[0, 0].set_xlabel('Prediction Error')

    # 2. Prediction vs True Label
    axes[0, 1].scatter(y_true, y_pred_probs.max(axis=1), alpha=0.4, color='#3498db')
    axes[0, 1].plot([0, len(class_names)-1], [0, 1], '--r', label='Perfect Prediction')
    axes[0, 1].set_title('Prediction vs True Label', fontweight='bold')

    # 3. Error Distribution by Class (Box Plot)
    sns.boxplot(x=y_true, y=errors, ax=axes[1, 0], palette='Blues')
    axes[1, 0].set_title('Error Distribution by Class', fontweight='bold')
    axes[1, 0].set_xticklabels(class_names, rotation=45)

    # 4. Confusion Matrix
    cm = confusion_matrix(y_true, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[1, 1],
                xticklabels=class_names, yticklabels=class_names)
    axes[1, 1].set_title('Confusion Matrix', fontweight='bold')

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()

plot_mobilenet_error_analysis(model_mobilenet, val_gen)

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

def plot_roc_curve(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    # Get probabilities for the positive class
    y_pred_probs = model.predict(val_gen)[:, 1]

    fpr, tpr, _ = roc_curve(y_true, y_pred_probs)
    roc_auc = auc(fpr, tpr)

    plt.figure(figsize=(8, 6))
    plt.plot(fpr, tpr, color='#005288', lw=2.5, label=f'AUC = {roc_auc:.3f}')
    plt.plot([0, 1], [0, 1], color='#d35400', linestyle='--', lw=2, label='Random')

    plt.title('MobileNetV2 - ROC Curve', fontweight='bold', fontsize=12)
    plt.xlabel('False Positive Rate', fontweight='bold')
    plt.ylabel('True Positive Rate', fontweight='bold')
    plt.grid(True, alpha=0.2, linestyle=':')
    plt.legend(loc="lower right")
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.show()

plot_roc_curve(model_mobilenet, val_gen)

from tensorflow.keras.applications import VGG16

base_vgg = VGG16(weights='imagenet', include_top=False, input_shape=(224,224,3))
base_vgg.trainable = False

model_vgg = models.Sequential([
    base_vgg,
    layers.GlobalAveragePooling2D(),
    layers.Dense(len(class_names), activation='softmax')
])

model_vgg.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
history_vgg = model_vgg.fit(train_gen, validation_data=val_gen, epochs=15)

import matplotlib.pyplot as plt

def plot_vgg_performance(history):
    # Training vs Validation Accuracy
    plt.figure(figsize=(9, 6))
    plt.plot(history.history['accuracy'], label='Training Accuracy',
             color='#2ecc71', marker='o', linewidth=2.5, markersize=5)
    plt.plot(history.history['val_accuracy'], label='Validation Accuracy',
             color='#e74c3c', marker='s', linewidth=2.5, markersize=5)
    plt.title('VGG16 - Training vs Validation Accuracy', fontweight='bold')
    plt.xlabel('Epoch', fontweight='bold')
    plt.ylabel('Accuracy', fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.show()

    # Training vs Validation Loss
    plt.figure(figsize=(9, 6))
    plt.plot(history.history['loss'], label='Training Loss',
             color='#3498db', marker='o', linewidth=2.5, markersize=5)
    plt.plot(history.history['val_loss'], label='Validation Loss',
             color='#f39c12', marker='s', linewidth=2.5, markersize=5)
    plt.title('VGG16 - Training vs Validation Loss', fontweight='bold')
    plt.xlabel('Epoch', fontweight='bold')
    plt.ylabel('Loss', fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.show()

plot_vgg_performance(history_vgg)

import numpy as np
import seaborn as sns
from sklearn.metrics import confusion_matrix

def plot_vgg_error_analysis(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)
    y_pred = np.argmax(y_pred_probs, axis=1)
    errors = np.abs(y_true - y_pred_probs.max(axis=1))

    fig, axes = plt.subplots(2, 2, figsize=(16, 12))
    fig.suptitle('VGG16 - Comprehensive Error Analysis', fontsize=16, fontweight='bold')

    # 1. Error Distribution
    axes[0, 0].hist(errors, bins=25, color='#e74c3c', alpha=0.7, edgecolor='black')
    axes[0, 0].set_title('Error Distribution', fontweight='bold')
    axes[0, 0].set_xlabel('Prediction Error')

    # 2. Prediction vs True Label
    axes[0, 1].scatter(y_true, y_pred_probs.max(axis=1), alpha=0.4, color='#3498db')
    axes[0, 1].plot([0, len(class_names)-1], [0, 1], '--r', label='Perfect Prediction')
    axes[0, 1].set_title('Prediction vs True Label', fontweight='bold')

    # 3. Error Distribution by Class (Box Plot)
    sns.boxplot(x=y_true, y=errors, ax=axes[1, 0], palette='Blues')
    axes[1, 0].set_title('Error Distribution by Class', fontweight='bold')
    axes[1, 0].set_xticklabels(class_names, rotation=45)

    # 4. Confusion Matrix
    cm = confusion_matrix(y_true, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[1, 1],
                xticklabels=class_names, yticklabels=class_names)
    axes[1, 1].set_title('Confusion Matrix', fontweight='bold')

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()

plot_vgg_error_analysis(model_vgg, val_gen)

def compare_vgg_vs_mobile():
    vgg_acc = history_vgg.history['val_accuracy'][-1]
    mobile_acc = history_mobilenet.history['val_accuracy'][-1]

    plt.figure(figsize=(8, 5))
    plt.bar(['VGG16', 'MobileNetV2'], [vgg_acc, mobile_acc], color=['#3498db', '#2ecc71'])
    plt.title('Validation Accuracy Comparison', fontweight='bold')
    plt.ylabel('Accuracy Score')
    plt.ylim(0, 1.0)
    for i, v in enumerate([vgg_acc, mobile_acc]):
        plt.text(i, v + 0.02, f"{v:.2f}", ha='center', fontweight='bold')
    plt.show()

compare_vgg_vs_mobile()

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

def plot_vgg_roc_curve(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    # Get probabilities for the positive class
    y_pred_probs = model.predict(val_gen)[:, 1]

    fpr, tpr, _ = roc_curve(y_true, y_pred_probs)
    roc_auc = auc(fpr, tpr)

    plt.figure(figsize=(8, 6))
    # Using the specific dark blue color from your image
    plt.plot(fpr, tpr, color='#005288', lw=2.5, label=f'AUC = {roc_auc:.3f}')
    # Orange dashed line for random chance
    plt.plot([0, 1], [0, 1], color='#d35400', linestyle='--', lw=2, label='Random')

    plt.title('VGG16 - ROC Curve', fontweight='bold', fontsize=12)
    plt.xlabel('False Positive Rate', fontweight='bold')
    plt.ylabel('True Positive Rate', fontweight='bold')
    plt.grid(True, alpha=0.2, linestyle=':')
    plt.legend(loc="lower right")
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.show()

# Run the function
plot_vgg_roc_curve(model_vgg, val_gen)

import numpy as np

def plot_vgg_probability_dist(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)[:, 1] # Probabilities for Class 1

    plt.figure(figsize=(12, 6))

    # Histogram for True Class 0 (Blue)
    plt.hist(y_pred_probs[y_true == 0], bins=25, alpha=0.5, label='Class 0 (True Label)',
             color='#3498db', edgecolor='black')

    # Histogram for True Class 1 (Red/Salmon)
    plt.hist(y_pred_probs[y_true == 1], bins=25, alpha=0.5, label='Class 1 (True Label)',
             color='#e74c3c', edgecolor='black')

    # Green dashed line for decision threshold
    plt.axvline(0.5, color='green', linestyle='--', linewidth=3, label='Decision Threshold (0.5)')

    plt.title('VGG16 - Prediction Probability Distribution', fontweight='bold', fontsize=14)
    plt.xlabel('Predicted Probability', fontweight='bold')
    plt.ylabel('Frequency', fontweight='bold')
    plt.legend()
    plt.grid(axis='y', alpha=0.3)
    plt.show()

# Run the function
plot_vgg_probability_dist(model_vgg, val_gen)

from tensorflow.keras.applications import ResNet50

base_resnet = ResNet50(weights='imagenet', include_top=False, input_shape=(224,224,3))
base_resnet.trainable = False

model_resnet = models.Sequential([
    base_resnet,
    layers.GlobalAveragePooling2D(),
    layers.Dense(len(class_names), activation='softmax')
])

model_resnet.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
history_resnet = model_resnet.fit(train_gen, validation_data=val_gen, epochs=15)

import matplotlib.pyplot as plt
import numpy as np

def plot_resnet_history(history):
    # Accuracy Plot
    plt.figure(figsize=(9, 6))
    plt.plot(history.history['accuracy'], label='Training Accuracy',
             color='#2ecc71', marker='o', linewidth=2.5)
    plt.plot(history.history['val_accuracy'], label='Validation Accuracy',
             color='#e74c3c', marker='s', linewidth=2.5)
    plt.title('ResNet50 - Training vs Validation Accuracy', fontweight='bold')
    plt.xlabel('Epoch', fontweight='bold')
    plt.ylabel('Accuracy', fontweight='bold')
    plt.ylim(0.4, 1.0)
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.show()

    # Loss Plot
    plt.figure(figsize=(9, 6))
    plt.plot(history.history['loss'], label='Training Loss',
             color='#3498db', marker='o', linewidth=2.5)
    plt.plot(history.history['val_loss'], label='Validation Loss',
             color='#f39c12', marker='s', linewidth=2.5)
    plt.title('ResNet50 - Training vs Validation Loss', fontweight='bold')
    plt.xlabel('Epoch', fontweight='bold')
    plt.ylabel('Loss', fontweight='bold')
    plt.ylim(0, 1.0)
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.show()

plot_resnet_history(history_resnet)

import seaborn as sns
from sklearn.metrics import confusion_matrix

def plot_resnet_error_analysis(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)
    y_pred = np.argmax(y_pred_probs, axis=1)

    # Calculate Prediction Error
    prediction_error = np.abs(y_true - y_pred_probs.max(axis=1))

    fig, axes = plt.subplots(2, 2, figsize=(16, 12))
    fig.suptitle('ResNet50 - Comprehensive Error Analysis', fontsize=16, fontweight='bold')

    # 1. Error Distribution Histogram
    axes[0, 0].hist(prediction_error, bins=25, color='#e74c3c', alpha=0.7, edgecolor='black')
    axes[0, 0].set_title('Error Distribution', fontweight='bold')
    axes[0, 0].set_xlabel('Prediction Error')

    # 2. Prediction vs True Label
    axes[0, 1].scatter(y_true, y_pred_probs.max(axis=1), alpha=0.4, color='#3498db')
    axes[0, 1].plot([0, len(class_names)-1], [0, 1], '--r', label='Perfect Prediction')
    axes[0, 1].set_title('Prediction vs True Label', fontweight='bold')

    # 3. Error Distribution by Class (Box Plot)
    sns.boxplot(x=y_true, y=prediction_error, ax=axes[1, 0], palette='Blues')
    axes[1, 0].set_title('Error Distribution by Class', fontweight='bold')
    axes[1, 0].set_xticklabels(class_names, rotation=45)

    # 4. Confusion Matrix
    cm = confusion_matrix(y_true, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[1, 1],
                xticklabels=class_names, yticklabels=class_names)
    axes[1, 1].set_title('Confusion Matrix', fontweight='bold')

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()

plot_resnet_error_analysis(model_resnet, val_gen)

from sklearn.metrics import roc_curve, auc

def plot_resnet_roc(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    # Get probabilities for positive class (adjust index if multi-class)
    y_pred_probs = model.predict(val_gen)[:, 1]

    fpr, tpr, _ = roc_curve(y_true, y_pred_probs)
    roc_auc = auc(fpr, tpr)

    plt.figure(figsize=(8, 6))
    plt.plot(fpr, tpr, color='#005288', lw=2.5, label=f'AUC = {roc_auc:.3f}')
    plt.plot([0, 1], [0, 1], color='#d35400', linestyle='--', label='Random')
    plt.title('ResNet50 - ROC Curve', fontweight='bold')
    plt.xlabel('False Positive Rate', fontweight='bold')
    plt.ylabel('True Positive Rate', fontweight='bold')
    plt.legend(loc="lower right")
    plt.grid(True, alpha=0.2, linestyle=':')
    plt.show()

plot_resnet_roc(model_resnet, val_gen)

import numpy as np
import matplotlib.pyplot as plt

def plot_probability_distribution(model, val_gen, model_name="ResNet50"):
    # Ensure generator is reset to align with ground truth
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)

    # We plot the probabilities for the positive class (Class 1)
    # Adjust this index if your 'Torn' class is at a different index
    pos_probs = y_pred_probs[:, 1]

    plt.figure(figsize=(12, 6))

    # Histogram for True Class 0 (e.g., 'New/Clean') - Light Blue
    plt.hist(pos_probs[y_true == 0], bins=25, alpha=0.5,
             label='No High Beam (True Label)', color='#3498db', edgecolor='black')

    # Histogram for True Class 1 (e.g., 'Torn/Old') - Salmon/Red
    plt.hist(pos_probs[y_true == 1], bins=25, alpha=0.5,
             label='High Beam (True Label)', color='#e74c3c', edgecolor='black')

    # Decision Threshold Line (Green Dashed)
    plt.axvline(0.5, color='green', linestyle='--', linewidth=3,
                label='Decision Threshold (0.5)')

    # Styling to match image_c19ac0.png
    plt.title(f'{model_name} - Prediction Probability Distribution\n(Model Confidence in High Beam Detection)',
              fontweight='bold', fontsize=12)
    plt.xlabel('Predicted Probability', fontweight='bold')
    plt.ylabel('Frequency', fontweight='bold')

    plt.legend(loc='upper center', bbox_to_anchor=(0.5, 1.0), ncol=1)
    plt.grid(axis='y', alpha=0.3)
    plt.xlim(0, 1.0)

    plt.tight_layout()
    plt.show()

# Run the function for your ResNet model
plot_probability_distribution(model_resnet, val_gen, "ResNet50")

from tensorflow.keras.applications import EfficientNetB0

base_eff = EfficientNetB0(weights='imagenet', include_top=False, input_shape=(224,224,3))
base_eff.trainable = False

model_eff = models.Sequential([
    base_eff,
    layers.GlobalAveragePooling2D(),
    layers.Dense(len(class_names), activation='softmax')
])

model_eff.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
history_eff = model_eff.fit(train_gen, validation_data=val_gen, epochs=15)

import matplotlib.pyplot as plt

def plot_efficientnet_history(history):
    # Accuracy Plot
    plt.figure(figsize=(9, 6))
    plt.plot(history.history['accuracy'], label='Training Accuracy',
             color='#2ecc71', marker='o', linewidth=2.5, markersize=5)
    plt.plot(history.history['val_accuracy'], label='Validation Accuracy',
             color='#e74c3c', marker='s', linewidth=2.5, markersize=5)
    plt.title('EfficientNetB0 - Training vs Validation Accuracy', fontweight='bold')
    plt.xlabel('Epoch', fontweight='bold')
    plt.ylabel('Accuracy', fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.show()

    # Loss Plot
    plt.figure(figsize=(9, 6))
    plt.plot(history.history['loss'], label='Training Loss',
             color='#3498db', marker='o', linewidth=2.5, markersize=5)
    plt.plot(history.history['val_loss'], label='Validation Loss',
             color='#f39c12', marker='s', linewidth=2.5, markersize=5)
    plt.title('EfficientNetB0 - Training vs Validation Loss', fontweight='bold')
    plt.xlabel('Epoch', fontweight='bold')
    plt.ylabel('Loss', fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.show()

plot_efficientnet_history(history_eff)

import numpy as np

def plot_eff_probability_distribution(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)
    pos_probs = y_pred_probs[:, 1] # Assuming Class 1 is 'Torn/Old'

    plt.figure(figsize=(12, 6))
    plt.hist(pos_probs[y_true == 0], bins=25, alpha=0.5, label='Clean (True Label)', color='#3498db', edgecolor='black')
    plt.hist(pos_probs[y_true == 1], bins=25, alpha=0.5, label='Torn (True Label)', color='#e74c3c', edgecolor='black')
    plt.axvline(0.5, color='green', linestyle='--', linewidth=3, label='Decision Threshold (0.5)')

    plt.title('EfficientNetB0 - Prediction Probability Distribution', fontweight='bold')
    plt.xlabel('Predicted Probability', fontweight='bold')
    plt.ylabel('Frequency', fontweight='bold')
    plt.legend()
    plt.grid(axis='y', alpha=0.3)
    plt.show()

plot_eff_probability_distribution(model_eff, val_gen)

import seaborn as sns
from sklearn.metrics import confusion_matrix

def plot_eff_error_analysis(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)
    y_pred = np.argmax(y_pred_probs, axis=1)
    errors = np.abs(y_true - y_pred_probs.max(axis=1))

    fig, axes = plt.subplots(2, 2, figsize=(16, 12))
    fig.suptitle('EfficientNetB0 - Comprehensive Error Analysis', fontsize=16, fontweight='bold')

    # Error Distribution Histogram
    axes[0, 0].hist(errors, bins=25, color='#e74c3c', alpha=0.7, edgecolor='black')
    axes[0, 0].set_title('Error Distribution', fontweight='bold')

    # Prediction vs True Label
    axes[0, 1].scatter(y_true, y_pred_probs.max(axis=1), alpha=0.4, color='#3498db')
    axes[0, 1].plot([0, len(class_names)-1], [0, 1], '--r', label='Perfect Prediction')
    axes[0, 1].set_title('Prediction vs True Label', fontweight='bold')

    # Error Distribution by Class
    sns.boxplot(x=y_true, y=errors, ax=axes[1, 0], palette='Blues')
    axes[1, 0].set_title('Error Distribution by Class', fontweight='bold')

    # Confusion Matrix
    cm = confusion_matrix(y_true, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[1, 1], xticklabels=class_names, yticklabels=class_names)
    axes[1, 1].set_title('Confusion Matrix', fontweight='bold')

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()

plot_eff_error_analysis(model_eff, val_gen)

from sklearn.metrics import roc_curve, auc

def plot_eff_roc(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)[:, 1]
    fpr, tpr, _ = roc_curve(y_true, y_pred_probs)
    roc_auc = auc(fpr, tpr)

    plt.figure(figsize=(8, 6))
    plt.plot(fpr, tpr, color='#005288', lw=2.5, label=f'AUC = {roc_auc:.3f}')
    plt.plot([0, 1], [0, 1], color='#d35400', linestyle='--', label='Random')
    plt.title('EfficientNetB0 - ROC Curve', fontweight='bold')
    plt.xlabel('False Positive Rate', fontweight='bold')
    plt.ylabel('True Positive Rate', fontweight='bold')
    plt.legend(loc="lower right")
    plt.grid(True, alpha=0.2, linestyle=':')
    plt.show()

plot_eff_roc(model_eff, val_gen)

from tensorflow.keras.applications import DenseNet121

base_densenet = DenseNet121(weights='imagenet', include_top=False, input_shape=(224,224,3))
base_densenet.trainable = False

model_densenet = models.Sequential([
    base_densenet,
    layers.GlobalAveragePooling2D(),
    layers.Dense(len(class_names), activation='softmax')
])

model_densenet.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
history_densenet = model_densenet.fit(train_gen, validation_data=val_gen, epochs=15)

import matplotlib.pyplot as plt

def plot_densenet_history(history):
    # Accuracy Plot (Matching Figure 3)
    plt.figure(figsize=(9, 6))
    plt.plot(history.history['accuracy'], label='Training Accuracy',
             color='#2ecc71', marker='o', linewidth=2.5, markersize=5)
    plt.plot(history.history['val_accuracy'], label='Validation Accuracy',
             color='#e74c3c', marker='s', linewidth=2.5, markersize=5)
    plt.title('DenseNet121 - Training vs Validation Accuracy', fontweight='bold')
    plt.xlabel('Epoch', fontweight='bold')
    plt.ylabel('Accuracy', fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.show()

    # Loss Plot (Matching Figure 4)
    plt.figure(figsize=(9, 6))
    plt.plot(history.history['loss'], label='Training Loss',
             color='#3498db', marker='o', linewidth=2.5, markersize=5)
    plt.plot(history.history['val_loss'], label='Validation Loss',
             color='#f39c12', marker='s', linewidth=2.5, markersize=5)
    plt.title('DenseNet121 - Training vs Validation Loss', fontweight='bold')
    plt.xlabel('Epoch', fontweight='bold')
    plt.ylabel('Loss', fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.show()

plot_densenet_history(history_densenet)

import numpy as np

def plot_densenet_prob_dist(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)
    pos_probs = y_pred_probs[:, 1] # Probability for 'Torn' class

    plt.figure(figsize=(12, 6))
    plt.hist(pos_probs[y_true == 0], bins=25, alpha=0.5, label='Clean (True Label)', color='#3498db', edgecolor='black')
    plt.hist(pos_probs[y_true == 1], bins=25, alpha=0.5, label='Torn (True Label)', color='#e74c3c', edgecolor='black')
    plt.axvline(0.5, color='green', linestyle='--', linewidth=3, label='Decision Threshold (0.5)')

    plt.title('DenseNet121 - Prediction Probability Distribution', fontweight='bold')
    plt.xlabel('Predicted Probability', fontweight='bold')
    plt.ylabel('Frequency', fontweight='bold')
    plt.legend()
    plt.grid(axis='y', alpha=0.3)
    plt.show()

plot_densenet_prob_dist(model_densenet, val_gen)

import seaborn as sns
from sklearn.metrics import confusion_matrix

def plot_densenet_error_analysis(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)
    y_pred = np.argmax(y_pred_probs, axis=1)
    errors = np.abs(y_true - y_pred_probs.max(axis=1))

    fig, axes = plt.subplots(2, 2, figsize=(16, 12))
    fig.suptitle('DenseNet121 - Comprehensive Error Analysis', fontsize=16, fontweight='bold')

    # Histogram: Error Distribution
    axes[0, 0].hist(errors, bins=25, color='#e74c3c', alpha=0.7, edgecolor='black')
    axes[0, 0].set_title('Error Distribution', fontweight='bold')

    # Scatter: Prediction vs True Label
    axes[0, 1].scatter(y_true, y_pred_probs.max(axis=1), alpha=0.4, color='#3498db')
    axes[0, 1].plot([0, len(class_names)-1], [0, 1], '--r', label='Perfect Prediction')
    axes[0, 1].set_title('Prediction vs True Label', fontweight='bold')

    # Box Plot: Error Distribution by Class
    sns.boxplot(x=y_true, y=errors, ax=axes[1, 0], palette='Blues')
    axes[1, 0].set_title('Error Distribution by Class', fontweight='bold')

    # Confusion Matrix (Matching Figure 7)
    cm = confusion_matrix(y_true, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[1, 1], xticklabels=class_names, yticklabels=class_names)
    axes[1, 1].set_title('Confusion Matrix', fontweight='bold')

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()

plot_densenet_error_analysis(model_densenet, val_gen)

from sklearn.metrics import roc_curve, auc

def plot_densenet_roc(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)[:, 1]
    fpr, tpr, _ = roc_curve(y_true, y_pred_probs)
    roc_auc = auc(fpr, tpr)

    plt.figure(figsize=(8, 6))
    plt.plot(fpr, tpr, color='#005288', lw=2.5, label=f'AUC = {roc_auc:.3f}')
    plt.plot([0, 1], [0, 1], color='#d35400', linestyle='--', label='Random')
    plt.title('DenseNet121 - ROC Curve', fontweight='bold')
    plt.xlabel('False Positive Rate', fontweight='bold')
    plt.ylabel('True Positive Rate', fontweight='bold')
    plt.legend(loc="lower right")
    plt.grid(True, alpha=0.2, linestyle=':')
    plt.show()

plot_densenet_roc(model_densenet, val_gen)

from tensorflow.keras.applications import InceptionV3

base_inception = InceptionV3(weights='imagenet', include_top=False, input_shape=(224,224,3))
base_inception.trainable = False

model_inception = models.Sequential([
    base_inception,
    layers.GlobalAveragePooling2D(),
    layers.Dense(len(class_names), activation='softmax')
])

model_inception.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
history_inception = model_inception.fit(train_gen, validation_data=val_gen, epochs=15)

import matplotlib.pyplot as plt

def plot_inception_history(history):
    # Accuracy Plot (Matching Figure 3)
    plt.figure(figsize=(9, 6))
    plt.plot(history.history['accuracy'], label='Training Accuracy',
             color='#2ecc71', marker='o', linewidth=2.5, markersize=5)
    plt.plot(history.history['val_accuracy'], label='Validation Accuracy',
             color='#e74c3c', marker='s', linewidth=2.5, markersize=5)
    plt.title('InceptionV3 - Training vs Validation Accuracy', fontweight='bold')
    plt.xlabel('Epoch', fontweight='bold')
    plt.ylabel('Accuracy', fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.show()

    # Loss Plot (Matching Figure 4)
    plt.figure(figsize=(9, 6))
    plt.plot(history.history['loss'], label='Training Loss',
             color='#3498db', marker='o', linewidth=2.5, markersize=5)
    plt.plot(history.history['val_loss'], label='Validation Loss',
             color='#f39c12', marker='s', linewidth=2.5, markersize=5)
    plt.title('InceptionV3 - Training vs Validation Loss', fontweight='bold')
    plt.xlabel('Epoch', fontweight='bold')
    plt.ylabel('Loss', fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.show()

plot_inception_history(history_inception)

import numpy as np

def plot_inception_prob_dist(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)
    pos_probs = y_pred_probs[:, 1] # Probability for the 'Torn' class

    plt.figure(figsize=(12, 6))
    plt.hist(pos_probs[y_true == 0], bins=25, alpha=0.5, label='Clean (True Label)', color='#3498db', edgecolor='black')
    plt.hist(pos_probs[y_true == 1], bins=25, alpha=0.5, label='Torn (True Label)', color='#e74c3c', edgecolor='black')
    plt.axvline(0.5, color='green', linestyle='--', linewidth=3, label='Decision Threshold (0.5)')

    plt.title('InceptionV3 - Prediction Probability Distribution', fontweight='bold')
    plt.xlabel('Predicted Probability', fontweight='bold')
    plt.ylabel('Frequency', fontweight='bold')
    plt.legend()
    plt.grid(axis='y', alpha=0.3)
    plt.show()

plot_inception_prob_dist(model_inception, val_gen)

import seaborn as sns
from sklearn.metrics import confusion_matrix

def plot_inception_error_analysis(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)
    y_pred = np.argmax(y_pred_probs, axis=1)
    errors = np.abs(y_true - y_pred_probs.max(axis=1))

    fig, axes = plt.subplots(2, 2, figsize=(16, 12))
    fig.suptitle('InceptionV3 - Comprehensive Error Analysis', fontsize=16, fontweight='bold')

    # Histogram: Error Distribution
    axes[0, 0].hist(errors, bins=25, color='#e74c3c', alpha=0.7, edgecolor='black')
    axes[0, 0].set_title('Error Distribution', fontweight='bold')

    # Scatter: Prediction vs True Label
    axes[0, 1].scatter(y_true, y_pred_probs.max(axis=1), alpha=0.4, color='#3498db')
    axes[0, 1].plot([0, len(class_names)-1], [0, 1], '--r', label='Perfect Prediction')
    axes[0, 1].set_title('Prediction vs True Label', fontweight='bold')

    # Box Plot: Error Distribution by Class
    sns.boxplot(x=y_true, y=errors, ax=axes[1, 0], palette='Blues')
    axes[1, 0].set_title('Error Distribution by Class', fontweight='bold')

    # Confusion Matrix (Matching Figure 7)
    cm = confusion_matrix(y_true, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[1, 1], xticklabels=class_names, yticklabels=class_names)
    axes[1, 1].set_title('Confusion Matrix', fontweight='bold')

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()

plot_inception_error_analysis(model_inception, val_gen)

from sklearn.metrics import roc_curve, auc

def plot_inception_roc(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)[:, 1]
    fpr, tpr, _ = roc_curve(y_true, y_pred_probs)
    roc_auc = auc(fpr, tpr)

    plt.figure(figsize=(8, 6))
    plt.plot(fpr, tpr, color='#005288', lw=2.5, label=f'AUC = {roc_auc:.3f}')
    plt.plot([0, 1], [0, 1], color='#d35400', linestyle='--', label='Random')
    plt.title('InceptionV3 - ROC Curve', fontweight='bold')
    plt.xlabel('False Positive Rate', fontweight='bold')
    plt.ylabel('True Positive Rate', fontweight='bold')
    plt.legend(loc="lower right")
    plt.grid(True, alpha=0.2, linestyle=':')
    plt.show()

plot_inception_roc(model_inception, val_gen)

from tensorflow.keras.applications import Xception

base_xception = Xception(weights='imagenet', include_top=False, input_shape=(224,224,3))
base_xception.trainable = False

model_xception = models.Sequential([
    base_xception,
    layers.GlobalAveragePooling2D(),
    layers.Dense(len(class_names), activation='softmax')
])

model_xception.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
history_xception = model_xception.fit(train_gen, validation_data=val_gen, epochs=15)

import matplotlib.pyplot as plt

def plot_xception_history(history):
    # Accuracy Plot (Matching Figure 3)
    plt.figure(figsize=(9, 6))
    plt.plot(history.history['accuracy'], label='Training Accuracy',
             color='#2ecc71', marker='o', linewidth=2.5, markersize=5)
    plt.plot(history.history['val_accuracy'], label='Validation Accuracy',
             color='#e74c3c', marker='s', linewidth=2.5, markersize=5)
    plt.title('Xception - Training vs Validation Accuracy', fontweight='bold')
    plt.xlabel('Epoch', fontweight='bold')
    plt.ylabel('Accuracy', fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.show()

    # Loss Plot (Matching Figure 4)
    plt.figure(figsize=(9, 6))
    plt.plot(history.history['loss'], label='Training Loss',
             color='#3498db', marker='o', linewidth=2.5, markersize=5)
    plt.plot(history.history['val_loss'], label='Validation Loss',
             color='#f39c12', marker='s', linewidth=2.5, markersize=5)
    plt.title('Xception - Training vs Validation Loss', fontweight='bold')
    plt.xlabel('Epoch', fontweight='bold')
    plt.ylabel('Loss', fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.show()

plot_xception_history(history_xception)

import numpy as np

def plot_xception_prob_dist(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)
    pos_probs = y_pred_probs[:, 1] # Probability for the 'Torn' class

    plt.figure(figsize=(12, 6))
    plt.hist(pos_probs[y_true == 0], bins=25, alpha=0.5, label='Clean (True Label)', color='#3498db', edgecolor='black')
    plt.hist(pos_probs[y_true == 1], bins=25, alpha=0.5, label='Torn (True Label)', color='#e74c3c', edgecolor='black')
    plt.axvline(0.5, color='green', linestyle='--', linewidth=3, label='Decision Threshold (0.5)')

    plt.title('Xception - Prediction Probability Distribution', fontweight='bold')
    plt.xlabel('Predicted Probability', fontweight='bold')
    plt.ylabel('Frequency', fontweight='bold')
    plt.legend()
    plt.grid(axis='y', alpha=0.3)
    plt.show()

plot_xception_prob_dist(model_xception, val_gen)

import seaborn as sns
from sklearn.metrics import confusion_matrix

def plot_xception_error_analysis(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)
    y_pred = np.argmax(y_pred_probs, axis=1)
    errors = np.abs(y_true - y_pred_probs.max(axis=1))

    fig, axes = plt.subplots(2, 2, figsize=(16, 12))
    fig.suptitle('Xception - Comprehensive Error Analysis', fontsize=16, fontweight='bold')

    # Histogram: Error Distribution
    axes[0, 0].hist(errors, bins=25, color='#e74c3c', alpha=0.7, edgecolor='black')
    axes[0, 0].set_title('Error Distribution', fontweight='bold')

    # Scatter: Prediction vs True Label
    axes[0, 1].scatter(y_true, y_pred_probs.max(axis=1), alpha=0.4, color='#3498db')
    axes[0, 1].plot([0, len(class_names)-1], [0, 1], '--r', label='Perfect Prediction')
    axes[0, 1].set_title('Prediction vs True Label', fontweight='bold')

    # Box Plot: Error Distribution by Class
    sns.boxplot(x=y_true, y=errors, ax=axes[1, 0], palette='Blues')
    axes[1, 0].set_title('Error Distribution by Class', fontweight='bold')

    # Confusion Matrix (Matching Figure 7)
    cm = confusion_matrix(y_true, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[1, 1], xticklabels=class_names, yticklabels=class_names)
    axes[1, 1].set_title('Confusion Matrix', fontweight='bold')

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()

plot_xception_error_analysis(model_xception, val_gen)

from sklearn.metrics import roc_curve, auc

def plot_xception_roc(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)[:, 1]
    fpr, tpr, _ = roc_curve(y_true, y_pred_probs)
    roc_auc = auc(fpr, tpr)

    plt.figure(figsize=(8, 6))
    plt.plot(fpr, tpr, color='#005288', lw=2.5, label=f'AUC = {roc_auc:.3f}')
    plt.plot([0, 1], [0, 1], color='#d35400', linestyle='--', label='Random')
    plt.title('Xception - ROC Curve', fontweight='bold')
    plt.xlabel('False Positive Rate', fontweight='bold')
    plt.ylabel('True Positive Rate', fontweight='bold')
    plt.legend(loc="lower right")
    plt.grid(True, alpha=0.2, linestyle=':')
    plt.show()

plot_xception_roc(model_xception, val_gen)

from tensorflow.keras.applications import NASNetMobile

base_nasnet = NASNetMobile(weights='imagenet', include_top=False, input_shape=(224,224,3))
base_nasnet.trainable = False

model_nasnet = models.Sequential([
    base_nasnet,
    layers.GlobalAveragePooling2D(),
    layers.Dense(len(class_names), activation='softmax')
])

model_nasnet.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
history_nasnet = model_nasnet.fit(train_gen, validation_data=val_gen, epochs=15)

import matplotlib.pyplot as plt

def plot_nasnet_history(history):
    # Accuracy Plot (Matching Figure 3)
    plt.figure(figsize=(9, 6))
    plt.plot(history.history['accuracy'], label='Training Accuracy',
             color='#2ecc71', marker='o', linewidth=2.5, markersize=5)
    plt.plot(history.history['val_accuracy'], label='Validation Accuracy',
             color='#e74c3c', marker='s', linewidth=2.5, markersize=5)
    plt.title('NASNetMobile - Training vs Validation Accuracy', fontweight='bold')
    plt.xlabel('Epoch', fontweight='bold')
    plt.ylabel('Accuracy', fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.show()

    # Loss Plot (Matching Figure 4)
    plt.figure(figsize=(9, 6))
    plt.plot(history.history['loss'], label='Training Loss',
             color='#3498db', marker='o', linewidth=2.5, markersize=5)
    plt.plot(history.history['val_loss'], label='Validation Loss',
             color='#f39c12', marker='s', linewidth=2.5, markersize=5)
    plt.title('NASNetMobile - Training vs Validation Loss', fontweight='bold')
    plt.xlabel('Epoch', fontweight='bold')
    plt.ylabel('Loss', fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.show()

plot_nasnet_history(history_nasnet)

import numpy as np

def plot_nasnet_prob_dist(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)
    pos_probs = y_pred_probs[:, 1] # Probability for the 'Torn' class

    plt.figure(figsize=(12, 6))
    plt.hist(pos_probs[y_true == 0], bins=25, alpha=0.5, label='Clean (True Label)', color='#3498db', edgecolor='black')
    plt.hist(pos_probs[y_true == 1], bins=25, alpha=0.5, label='Torn (True Label)', color='#e74c3c', edgecolor='black')
    plt.axvline(0.5, color='green', linestyle='--', linewidth=3, label='Decision Threshold (0.5)')

    plt.title('NASNetMobile - Prediction Probability Distribution', fontweight='bold')
    plt.xlabel('Predicted Probability', fontweight='bold')
    plt.ylabel('Frequency', fontweight='bold')
    plt.legend()
    plt.grid(axis='y', alpha=0.3)
    plt.show()

plot_nasnet_prob_dist(model_nasnet, val_gen)

import seaborn as sns
from sklearn.metrics import confusion_matrix

def plot_nasnet_error_analysis(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)
    y_pred = np.argmax(y_pred_probs, axis=1)
    errors = np.abs(y_true - y_pred_probs.max(axis=1))

    fig, axes = plt.subplots(2, 2, figsize=(16, 12))
    fig.suptitle('NASNetMobile - Comprehensive Error Analysis', fontsize=16, fontweight='bold')

    # Histogram: Error Distribution
    axes[0, 0].hist(errors, bins=25, color='#e74c3c', alpha=0.7, edgecolor='black')
    axes[0, 0].set_title('Error Distribution', fontweight='bold')

    # Scatter: Prediction vs True Label
    axes[0, 1].scatter(y_true, y_pred_probs.max(axis=1), alpha=0.4, color='#3498db')
    axes[0, 1].plot([0, len(class_names)-1], [0, 1], '--r', label='Perfect Prediction')
    axes[0, 1].set_title('Prediction vs True Label', fontweight='bold')

    # Box Plot: Error Distribution by Class
    sns.boxplot(x=y_true, y=errors, ax=axes[1, 0], palette='Blues')
    axes[1, 0].set_title('Error Distribution by Class', fontweight='bold')

    # Confusion Matrix (Matching Figure 7)
    cm = confusion_matrix(y_true, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[1, 1], xticklabels=class_names, yticklabels=class_names)
    axes[1, 1].set_title('Confusion Matrix', fontweight='bold')

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()

plot_nasnet_error_analysis(model_nasnet, val_gen)

from sklearn.metrics import roc_curve, auc

def plot_nasnet_roc(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)[:, 1]
    fpr, tpr, _ = roc_curve(y_true, y_pred_probs)
    roc_auc = auc(fpr, tpr)

    plt.figure(figsize=(8, 6))
    plt.plot(fpr, tpr, color='#005288', lw=2.5, label=f'AUC = {roc_auc:.3f}')
    plt.plot([0, 1], [0, 1], color='#d35400', linestyle='--', label='Random')
    plt.title('NASNetMobile - ROC Curve', fontweight='bold')
    plt.xlabel('False Positive Rate', fontweight='bold')
    plt.ylabel('True Positive Rate', fontweight='bold')
    plt.legend(loc="lower right")
    plt.grid(True, alpha=0.2, linestyle=':')
    plt.show()

plot_nasnet_roc(model_nasnet, val_gen)

from tensorflow.keras.applications import MobileNetV3Small

base_mv3_small = MobileNetV3Small(weights='imagenet', include_top=False, input_shape=(224,224,3))
base_mv3_small.trainable = False

model_mv3_small = models.Sequential([
    base_mv3_small,
    layers.GlobalAveragePooling2D(),
    layers.Dense(len(class_names), activation='softmax')
])

model_mv3_small.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
history_mv3_small = model_mv3_small.fit(train_gen, validation_data=val_gen, epochs=15)

import matplotlib.pyplot as plt

def plot_mobilenet_v3_history(history):
    # Accuracy Plot (Matching Figure 3)
    plt.figure(figsize=(9, 6))
    plt.plot(history.history['accuracy'], label='Training Accuracy',
             color='#2ecc71', marker='o', linewidth=2.5, markersize=5)
    plt.plot(history.history['val_accuracy'], label='Validation Accuracy',
             color='#e74c3c', marker='s', linewidth=2.5, markersize=5)
    plt.title('MobileNetV3Small - Training vs Validation Accuracy', fontweight='bold')
    plt.xlabel('Epoch', fontweight='bold')
    plt.ylabel('Accuracy', fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.show()

    # Loss Plot (Matching Figure 4)
    plt.figure(figsize=(9, 6))
    plt.plot(history.history['loss'], label='Training Loss',
             color='#3498db', marker='o', linewidth=2.5, markersize=5)
    plt.plot(history.history['val_loss'], label='Validation Loss',
             color='#f39c12', marker='s', linewidth=2.5, markersize=5)
    plt.title('MobileNetV3Small - Training vs Validation Loss', fontweight='bold')
    plt.xlabel('Epoch', fontweight='bold')
    plt.ylabel('Loss', fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.show()

plot_mobilenet_v3_history(history_mv3_small)

import numpy as np

def plot_mv3_prob_dist(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)
    pos_probs = y_pred_probs[:, 1] # Probability for the 'Torn' class

    plt.figure(figsize=(12, 6))
    plt.hist(pos_probs[y_true == 0], bins=25, alpha=0.5, label='Clean (True Label)', color='#3498db', edgecolor='black')
    plt.hist(pos_probs[y_true == 1], bins=25, alpha=0.5, label='Torn (True Label)', color='#e74c3c', edgecolor='black')
    plt.axvline(0.5, color='green', linestyle='--', linewidth=3, label='Decision Threshold (0.5)')

    plt.title('MobileNetV3Small - Prediction Probability Distribution', fontweight='bold')
    plt.xlabel('Predicted Probability', fontweight='bold')
    plt.ylabel('Frequency', fontweight='bold')
    plt.legend()
    plt.grid(axis='y', alpha=0.3)
    plt.show()

plot_mv3_prob_dist(model_mv3_small, val_gen)

import seaborn as sns
from sklearn.metrics import confusion_matrix

def plot_mv3_error_analysis(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)
    y_pred = np.argmax(y_pred_probs, axis=1)
    errors = np.abs(y_true - y_pred_probs.max(axis=1))

    fig, axes = plt.subplots(2, 2, figsize=(16, 12))
    fig.suptitle('MobileNetV3Small - Comprehensive Error Analysis', fontsize=16, fontweight='bold')

    # Histogram: Error Distribution
    axes[0, 0].hist(errors, bins=25, color='#e74c3c', alpha=0.7, edgecolor='black')
    axes[0, 0].set_title('Error Distribution', fontweight='bold')

    # Scatter: Prediction vs True Label
    axes[0, 1].scatter(y_true, y_pred_probs.max(axis=1), alpha=0.4, color='#3498db')
    axes[0, 1].plot([0, len(class_names)-1], [0, 1], '--r', label='Perfect Prediction')
    axes[0, 1].set_title('Prediction vs True Label', fontweight='bold')

    # Box Plot: Error Distribution by Class
    sns.boxplot(x=y_true, y=errors, ax=axes[1, 0], palette='Blues')
    axes[1, 0].set_title('Error Distribution by Class', fontweight='bold')

    # Confusion Matrix (Matching Figure 7)
    cm = confusion_matrix(y_true, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[1, 1], xticklabels=class_names, yticklabels=class_names)
    axes[1, 1].set_title('Confusion Matrix', fontweight='bold')

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()

plot_mv3_error_analysis(model_mv3_small, val_gen)

from sklearn.metrics import roc_curve, auc

def plot_mv3_roc(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)[:, 1]
    fpr, tpr, _ = roc_curve(y_true, y_pred_probs)
    roc_auc = auc(fpr, tpr)

    plt.figure(figsize=(8, 6))
    plt.plot(fpr, tpr, color='#005288', lw=2.5, label=f'AUC = {roc_auc:.3f}')
    plt.plot([0, 1], [0, 1], color='#d35400', linestyle='--', label='Random')
    plt.title('MobileNetV3Small - ROC Curve', fontweight='bold')
    plt.xlabel('False Positive Rate', fontweight='bold')
    plt.ylabel('True Positive Rate', fontweight='bold')
    plt.legend(loc="lower right")
    plt.grid(True, alpha=0.2, linestyle=':')
    plt.show()

plot_mv3_roc(model_mv3_small, val_gen)

import matplotlib.pyplot as plt
import numpy as np

def plot_master_benchmark():
    # 1. Collect names of all models
    model_names = [
        'VGG16', 'ResNet50', 'MobileNetV2', 'EfficientNetB0',
        'DenseNet121', 'InceptionV3', 'Xception', 'NASNetMobile',
        'MobileNetV3Small', 'YOLOv8-cls'
    ]

    # 2. Extract final validation accuracy from each history object
    # If YOLO was trained separately, manually input its best accuracy
    accuracies = [
        history_vgg.history['val_accuracy'][-1],
        history_resnet.history['val_accuracy'][-1],
        history_mobilenet.history['val_accuracy'][-1],
        history_eff.history['val_accuracy'][-1],
        history_densenet.history['val_accuracy'][-1],
        history_inception.history['val_accuracy'][-1],
        history_xception.history['val_accuracy'][-1],
        history_nasnet.history['val_accuracy'][-1],
        history_mv3_small.history['val_accuracy'][-1],
        0.94  # Example YOLO accuracy; replace with your actual best result
    ]

    # Sort models by performance (highest to lowest)
    sorted_indices = np.argsort(accuracies)[::-1]
    sorted_names = [model_names[i] for i in sorted_indices]
    sorted_accs = [accuracies[i] for i in sorted_indices]

    # 3. Generate the Visualization
    plt.figure(figsize=(15, 8))

    # Use a distinct color palette (Viridis)
    colors = plt.cm.viridis(np.linspace(0, 1, len(sorted_names)))
    bars = plt.bar(sorted_names, sorted_accs, color=colors, edgecolor='black', linewidth=1.2)

    # Styling to match your documentation
    plt.title('Master Model Benchmarking: Final Validation Accuracy Comparison',
              fontsize=18, fontweight='bold', pad=20)
    plt.ylabel('Accuracy Score', fontsize=14, fontweight='bold')
    plt.xlabel('Deep Learning Architecture', fontsize=14, fontweight='bold')
    plt.xticks(rotation=45, ha='right', fontsize=12)
    plt.ylim(0, 1.1)
    plt.grid(axis='y', linestyle='--', alpha=0.3)

    # Add value labels on top of each bar
    for bar in bars:
        height = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2., height + 0.02,
                 f'{height:.4f}', ha='center', va='bottom',
                 fontweight='bold', fontsize=11)

    plt.tight_layout()
    plt.show()

# Run the master comparison
plot_master_benchmark()

from tensorflow.keras.applications import MobileNetV3Large
from tensorflow.keras import layers, models

# Due to issues with 'classification-models-keras', replacing ShuffleNetV2 with MobileNetV3Large
base_mv3_large = MobileNetV3Large(input_shape=(224, 224, 3), weights='imagenet', include_top=False)
base_mv3_large.trainable = False

model_mv3_large = models.Sequential([
    base_mv3_large,
    layers.GlobalAveragePooling2D(),
    layers.Dense(len(class_names), activation='softmax')
])

model_mv3_large.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
history_mv3_large = model_mv3_large.fit(train_gen, validation_data=val_gen, epochs=15)

def plot_mobilenet_v3_large_history(history):
    # Accuracy
    plt.figure(figsize=(9, 6))
    plt.plot(history.history['accuracy'], label='Training Accuracy', color='#2ecc71', marker='o')
    plt.plot(history.history['val_accuracy'], label='Validation Accuracy', color='#e74c3c', marker='s')
    plt.title('MobileNetV3Large - Training vs Validation Accuracy', fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.show()

    # Loss
    plt.figure(figsize=(9, 6))
    plt.plot(history.history['loss'], label='Training Loss', color='#3498db', marker='o')
    plt.plot(history.history['val_loss'], label='Validation Loss', color='#f39c12', marker='s')
    plt.title('MobileNetV3Large - Training vs Validation Loss', fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.show()

plot_mobilenet_v3_large_history(history_mv3_large)

def plot_mv3_large_prob_dist(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)[:, 1] # Probability for 'Torn' class

    plt.figure(figsize=(12, 6))
    plt.hist(y_pred_probs[y_true == 0], bins=25, alpha=0.5, label='Clean', color='#3498db', edgecolor='black')
    plt.hist(y_pred_probs[y_true == 1], bins=25, alpha=0.5, label='Torn', color='#e74c3c', edgecolor='black')
    plt.axvline(0.5, color='green', linestyle='--', linewidth=3, label='Threshold')
    plt.title('MobileNetV3Large - Probability Distribution', fontweight='bold')
    plt.legend()
    plt.show()

plot_mv3_large_prob_dist(model_mv3_large, val_gen)

import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

def plot_mv3_large_error_analysis(model, val_gen):
    # 1. Prepare Data
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)
    y_pred = np.argmax(y_pred_probs, axis=1)

    # Calculate absolute error for each prediction
    errors = np.abs(y_true - y_pred_probs.max(axis=1))

    # 2. Create Figure Dashboard
    fig, axes = plt.subplots(2, 2, figsize=(16, 12))
    fig.suptitle('MobileNetV3Large - Comprehensive Error Analysis', fontsize=16, fontweight='bold')

    # Panel 1: Histogram - Error Distribution
    axes[0, 0].hist(errors, bins=25, color='#e74c3c', alpha=0.7, edgecolor='black')
    axes[0, 0].set_title('Error Distribution', fontweight='bold')
    axes[0, 0].set_xlabel('Prediction Error')
    axes[0, 0].set_ylabel('Frequency')

    # Panel 2: Scatter - Prediction vs True Label
    axes[0, 1].scatter(y_true, y_pred_probs.max(axis=1), alpha=0.4, color='#3498db')
    axes[0, 1].plot([0, len(class_names)-1], [0, 1], '--r', label='Perfect Prediction')
    axes[0, 1].set_title('Prediction vs True Label', fontweight='bold')
    axes[0, 1].set_xlabel('True Label Index')
    axes[0, 1].set_ylabel('Confidence Level')

    # Panel 3: Box Plot - Error Distribution by Class
    sns.boxplot(x=y_true, y=errors, ax=axes[1, 0], palette='Blues')
    axes[1, 0].set_title('Error Distribution by Class', fontweight='bold')
    axes[1, 0].set_xticklabels(class_names, rotation=45)
    axes[1, 0].set_ylabel('Error Magnitude')

    # Panel 4: Confusion Matrix (Matching Project Reference Fig 7)
    cm = confusion_matrix(y_true, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[1, 1],
                xticklabels=class_names, yticklabels=class_names)
    axes[1, 1].set_title('Confusion Matrix', fontweight='bold')
    axes[1, 1].set_xlabel('Predicted Label')
    axes[1, 1].set_ylabel('True Label')

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()

# Run the analysis for MobileNetV3Large
plot_mv3_large_error_analysis(model_mv3_large, val_gen)

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

def plot_mv3_large_roc(model, val_gen):
    # 1. Prepare Validation Data
    val_gen.reset()
    y_true = val_gen.classes

    # 2. Get probabilities for the positive class (e.g., Index 1: 'Torn')
    # If your classes are different, adjust the index [:, 1] accordingly
    y_pred_probs = model.predict(val_gen)[:, 1]

    # 3. Calculate FPR, TPR, and AUC score
    fpr, tpr, _ = roc_curve(y_true, y_pred_probs)
    roc_auc = auc(fpr, tpr)

    # 4. Generate Visualization
    plt.figure(figsize=(8, 6))

    # Dark blue line for the model curve
    plt.plot(fpr, tpr, color='#005288', lw=2.5, label=f'AUC = {roc_auc:.3f}')

    # Orange dashed line for random chance
    plt.plot([0, 1], [0, 1], color='#d35400', linestyle='--', lw=2, label='Random')

    # Styling to match project standard
    plt.title('MobileNetV3Large - ROC Curve', fontweight='bold', fontsize=12)
    plt.xlabel('False Positive Rate', fontweight='bold')
    plt.ylabel('True Positive Rate', fontweight='bold')

    # Legend and grid settings
    plt.legend(loc="lower right")
    plt.grid(True, alpha=0.2, linestyle=':')
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])

    plt.show()

# Run the ROC analysis for MobileNetV3Large
plot_mv3_large_roc(model_mv3_large, val_gen)

import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.applications import ResNet50

def squeeze_excite_block(input_tensor, ratio=16):
    """ Create a channel-wise Squeeze-and-Excitation block """
    init = input_tensor
    channel_axis = -1
    filters = init.shape[channel_axis]
    se_shape = (1, 1, filters)

    se = layers.GlobalAveragePooling2D()(init)
    se = layers.Reshape(se_shape)(se)
    se = layers.Dense(filters // ratio, activation='relu', kernel_initializer='he_normal', use_bias=False)(se)
    se = layers.Dense(filters, activation='sigmoid', kernel_initializer='he_normal', use_bias=False)(se)

    x = layers.Multiply()([init, se])
    return x

# 1. Load Base ResNet50
base_resnet = ResNet50(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
base_resnet.trainable = False

# 2. Add SE Block to the output of the base model
x = base_resnet.output
x = squeeze_excite_block(x)

# 3. Add Custom Head
x = layers.GlobalAveragePooling2D()(x)
output = layers.Dense(len(class_names), activation='softmax')(x)

model_se_resnet = models.Model(inputs=base_resnet.input, outputs=output)

model_se_resnet.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
history_se_resnet = model_se_resnet.fit(train_gen, validation_data=val_gen, epochs=15)

import matplotlib.pyplot as plt

def plot_se_resnet_history(history):
    # Accuracy Plot (Matching Figure 3)
    plt.figure(figsize=(9, 6))
    plt.plot(history.history['accuracy'], label='Training Accuracy',
             color='#2ecc71', marker='o', linewidth=2.5, markersize=5)
    plt.plot(history.history['val_accuracy'], label='Validation Accuracy',
             color='#e74c3c', marker='s', linewidth=2.5, markersize=5)
    plt.title('SE-ResNet50 - Training vs Validation Accuracy', fontweight='bold')
    plt.xlabel('Epoch', fontweight='bold')
    plt.ylabel('Accuracy', fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.show()

    # Loss Plot (Matching Figure 4)
    plt.figure(figsize=(9, 6))
    plt.plot(history.history['loss'], label='Training Loss',
             color='#3498db', marker='o', linewidth=2.5, markersize=5)
    plt.plot(history.history['val_loss'], label='Validation Loss',
             color='#f39c12', marker='s', linewidth=2.5, markersize=5)
    plt.title('SE-ResNet50 - Training vs Validation Loss', fontweight='bold')
    plt.xlabel('Epoch', fontweight='bold')
    plt.ylabel('Loss', fontweight='bold')
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.show()

plot_se_resnet_history(history_se_resnet)

import numpy as np

def plot_se_resnet_prob_dist(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)
    pos_probs = y_pred_probs[:, 1] # Probability for the 'Torn' class

    plt.figure(figsize=(12, 6))
    plt.hist(pos_probs[y_true == 0], bins=25, alpha=0.5, label='Clean (True Label)', color='#3498db', edgecolor='black')
    plt.hist(pos_probs[y_true == 1], bins=25, alpha=0.5, label='Torn (True Label)', color='#e74c3c', edgecolor='black')
    plt.axvline(0.5, color='green', linestyle='--', linewidth=3, label='Decision Threshold (0.5)')

    plt.title('SE-ResNet50 - Prediction Probability Distribution', fontweight='bold')
    plt.xlabel('Predicted Probability', fontweight='bold')
    plt.ylabel('Frequency', fontweight='bold')
    plt.legend()
    plt.grid(axis='y', alpha=0.3)
    plt.show()

plot_se_resnet_prob_dist(model_se_resnet, val_gen)



import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

def plot_se_resnet_error_analysis(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)
    y_pred = np.argmax(y_pred_probs, axis=1)
    errors = np.abs(y_true - y_pred_probs.max(axis=1))

    fig, axes = plt.subplots(2, 2, figsize=(16, 12))
    fig.suptitle('SE-ResNet50 - Comprehensive Error Analysis', fontsize=16, fontweight='bold')

    # Panel 1: Error Distribution
    axes[0, 0].hist(errors, bins=25, color='#e74c3c', alpha=0.7, edgecolor='black')
    axes[0, 0].set_title('Error Distribution', fontweight='bold')

    # Panel 2: Prediction vs True Label
    axes[0, 1].scatter(y_true, y_pred_probs.max(axis=1), alpha=0.4, color='#3498db')
    axes[0, 1].plot([0, len(class_names)-1], [0, 1], '--r', label='Perfect Prediction')
    axes[0, 1].set_title('Prediction vs True Label', fontweight='bold')

    # Panel 3: Error Distribution by Class
    sns.boxplot(x=y_true, y=errors, ax=axes[1, 0], palette='Blues')
    axes[1, 0].set_title('Error Distribution by Class', fontweight='bold')
    axes[1, 0].set_xticklabels(class_names, rotation=45)

    # Panel 4: Confusion Matrix (Matching Fig 7)
    cm = confusion_matrix(y_true, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[1, 1],
                xticklabels=class_names, yticklabels=class_names)
    axes[1, 1].set_title('Confusion Matrix', fontweight='bold')

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()

plot_se_resnet_error_analysis(model_se_resnet, val_gen)

from sklearn.metrics import roc_curve, auc

def plot_se_resnet_roc(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)[:, 1]
    fpr, tpr, _ = roc_curve(y_true, y_pred_probs)
    roc_auc = auc(fpr, tpr)

    plt.figure(figsize=(8, 6))
    plt.plot(fpr, tpr, color='#005288', lw=2.5, label=f'AUC = {roc_auc:.3f}')
    plt.plot([0, 1], [0, 1], color='#d35400', linestyle='--', label='Random')
    plt.title('SE-ResNet50 - ROC Curve', fontweight='bold')
    plt.xlabel('False Positive Rate', fontweight='bold')
    plt.ylabel('True Positive Rate', fontweight='bold')
    plt.legend(loc="lower right")
    plt.grid(True, alpha=0.2, linestyle=':')
    plt.show()

plot_se_resnet_roc(model_se_resnet, val_gen)

import tensorflow as tf
from tensorflow.keras import layers, models

def build_alexnet(input_shape, num_classes):
    model = models.Sequential([
        # Layer 1: Convolutional + Max Pooling
        layers.Conv2D(96, (11, 11), strides=4, padding='same', activation='relu', input_shape=input_shape),
        layers.BatchNormalization(),
        layers.MaxPooling2D((3, 3), strides=2),

        # Layer 2: Convolutional + Max Pooling
        layers.Conv2D(256, (5, 5), padding='same', activation='relu'),
        layers.BatchNormalization(),
        layers.MaxPooling2D((3, 3), strides=2),

        # Layer 3, 4, 5: Convolutional
        layers.Conv2D(384, (3, 3), padding='same', activation='relu'),
        layers.Conv2D(384, (3, 3), padding='same', activation='relu'),
        layers.Conv2D(256, (3, 3), padding='same', activation='relu'),
        layers.MaxPooling2D((3, 3), strides=2),

        # Layer 6, 7: Fully Connected
        layers.Flatten(),
        layers.Dense(4096, activation='relu'),
        layers.Dropout(0.5),
        layers.Dense(4096, activation='relu'),
        layers.Dropout(0.5),

        # Output Layer
        layers.Dense(num_classes, activation='softmax')
    ])
    return model

model_alexnet = build_alexnet((224, 224, 3), len(class_names))
model_alexnet.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
history_alexnet = model_alexnet.fit(train_gen, validation_data=val_gen, epochs=15)

import matplotlib.pyplot as plt

def plot_alexnet_history(history):
    # Accuracy Plot (Matching Figure 3)
    plt.figure(figsize=(9, 6))
    plt.plot(history.history['accuracy'], label='Training Accuracy', color='#2ecc71', marker='o', linewidth=2.5)
    plt.plot(history.history['val_accuracy'], label='Validation Accuracy', color='#e74c3c', marker='s', linewidth=2.5)
    plt.title('AlexNet - Training vs Validation Accuracy', fontweight='bold')
    plt.xlabel('Epoch'), plt.ylabel('Accuracy')
    plt.grid(True, alpha=0.3), plt.legend()
    plt.show()

    # Loss Plot (Matching Figure 4)
    plt.figure(figsize=(9, 6))
    plt.plot(history.history['loss'], label='Training Loss', color='#3498db', marker='o', linewidth=2.5)
    plt.plot(history.history['val_loss'], label='Validation Loss', color='#f39c12', marker='s', linewidth=2.5)
    plt.title('AlexNet - Training vs Validation Loss', fontweight='bold')
    plt.xlabel('Epoch'), plt.ylabel('Loss')
    plt.grid(True, alpha=0.3), plt.legend()
    plt.show()

plot_alexnet_history(history_alexnet)

import numpy as np

def plot_alexnet_prob_dist(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)[:, 1] # Probability for 'Torn'

    plt.figure(figsize=(12, 6))
    plt.hist(y_pred_probs[y_true == 0], bins=25, alpha=0.5, label='Clean', color='#3498db', edgecolor='black')
    plt.hist(y_pred_probs[y_true == 1], bins=25, alpha=0.5, label='Torn', color='#e74c3c', edgecolor='black')
    plt.axvline(0.5, color='green', linestyle='--', linewidth=3, label='Threshold')
    plt.title('AlexNet - Prediction Probability Distribution', fontweight='bold')
    plt.legend(), plt.show()

plot_alexnet_prob_dist(model_alexnet, val_gen)

import seaborn as sns
from sklearn.metrics import confusion_matrix

def plot_alexnet_error_analysis(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)
    y_pred = np.argmax(y_pred_probs, axis=1)
    errors = np.abs(y_true - y_pred_probs.max(axis=1))

    fig, axes = plt.subplots(2, 2, figsize=(16, 12))
    fig.suptitle('AlexNet - Comprehensive Error Analysis', fontsize=16, fontweight='bold')

    axes[0, 0].hist(errors, bins=25, color='#e74c3c', alpha=0.7, edgecolor='black')
    axes[0, 0].set_title('Error Distribution')

    axes[0, 1].scatter(y_true, y_pred_probs.max(axis=1), alpha=0.4, color='#3498db')
    axes[0, 1].set_title('Prediction vs True Label')

    sns.boxplot(x=y_true, y=errors, ax=axes[1, 0], palette='Blues')
    axes[1, 0].set_title('Error by Class')

    cm = confusion_matrix(y_true, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[1, 1], xticklabels=class_names, yticklabels=class_names)
    axes[1, 1].set_title('Confusion Matrix')

    plt.tight_layout(rect=[0, 0.03, 1, 0.95]), plt.show()

plot_alexnet_error_analysis(model_alexnet, val_gen)

from sklearn.metrics import roc_curve, auc

def plot_alexnet_roc(model, val_gen):
    val_gen.reset()
    y_pred_probs = model.predict(val_gen)[:, 1]
    fpr, tpr, _ = roc_curve(val_gen.classes, y_pred_probs)
    roc_auc = auc(fpr, tpr)

    plt.figure(figsize=(8, 6))
    plt.plot(fpr, tpr, color='#005288', lw=2.5, label=f'AUC = {roc_auc:.3f}')
    plt.plot([0, 1], [0, 1], color='#d35400', linestyle='--')
    plt.title('AlexNet - ROC Curve', fontweight='bold')
    plt.legend(loc="lower right"), plt.grid(True, alpha=0.2), plt.show()

plot_alexnet_roc(model_alexnet, val_gen)

import tensorflow as tf
from tensorflow.keras import layers, models

def build_custom_cnn(input_shape, num_classes):
    model = models.Sequential([
        # Block 1: Initial Feature Extraction
        layers.Conv2D(32, (3, 3), activation='relu', input_shape=input_shape),
        layers.BatchNormalization(),
        layers.MaxPooling2D((2, 2)),

        # Block 2: Learning Textures (Cracks/Tears)
        layers.Conv2D(64, (3, 3), activation='relu'),
        layers.BatchNormalization(),
        layers.MaxPooling2D((2, 2)),

        # Block 3: Higher Level Features
        layers.Conv2D(128, (3, 3), activation='relu'),
        layers.BatchNormalization(),
        layers.MaxPooling2D((2, 2)),

        # Block 4: Deep Spatial Understanding
        layers.Conv2D(128, (3, 3), activation='relu'),
        layers.MaxPooling2D((2, 2)),

        # Classification Head
        layers.Flatten(),
        layers.Dense(512, activation='relu'),
        layers.Dropout(0.5), # Prevents overfitting to specific shoe colors
        layers.Dense(num_classes, activation='softmax')
    ])
    return model

model_custom = build_custom_cnn((224, 224, 3), len(class_names))
model_custom.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
history_custom = model_custom.fit(train_gen, validation_data=val_gen, epochs=15)

import matplotlib.pyplot as plt

def plot_custom_history(history):
    # Accuracy Plot (Matching Figure 3)
    plt.figure(figsize=(9, 6))
    plt.plot(history.history['accuracy'], label='Training Accuracy', color='#2ecc71', marker='o', linewidth=2.5)
    plt.plot(history.history['val_accuracy'], label='Validation Accuracy', color='#e74c3c', marker='s', linewidth=2.5)
    plt.title('Custom CNN - Training vs Validation Accuracy', fontweight='bold')
    plt.xlabel('Epoch'), plt.ylabel('Accuracy')
    plt.grid(True, alpha=0.3), plt.legend()
    plt.show()

    # Loss Plot (Matching Figure 4)
    plt.figure(figsize=(9, 6))
    plt.plot(history.history['loss'], label='Training Loss', color='#3498db', marker='o', linewidth=2.5)
    plt.plot(history.history['val_loss'], label='Validation Loss', color='#f39c12', marker='s', linewidth=2.5)
    plt.title('Custom CNN - Training vs Validation Loss', fontweight='bold')
    plt.xlabel('Epoch'), plt.ylabel('Loss')
    plt.grid(True, alpha=0.3), plt.legend()
    plt.show()

plot_custom_history(history_custom)

import numpy as np

def plot_custom_prob_dist(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)[:, 1] # Assuming Index 1 is the 'Torn' class

    plt.figure(figsize=(12, 6))
    plt.hist(y_pred_probs[y_true == 0], bins=25, alpha=0.5, label='Clean', color='#3498db', edgecolor='black')
    plt.hist(y_pred_probs[y_true == 1], bins=25, alpha=0.5, label='Torn', color='#e74c3c', edgecolor='black')
    plt.axvline(0.5, color='green', linestyle='--', linewidth=3, label='Decision Threshold')
    plt.title('Custom CNN - Prediction Probability Distribution', fontweight='bold')
    plt.legend(), plt.show()

plot_custom_prob_dist(model_custom, val_gen)

import seaborn as sns
from sklearn.metrics import confusion_matrix

def plot_custom_error_analysis(model, val_gen):
    val_gen.reset()
    y_true = val_gen.classes
    y_pred_probs = model.predict(val_gen)
    y_pred = np.argmax(y_pred_probs, axis=1)
    errors = np.abs(y_true - y_pred_probs.max(axis=1))

    fig, axes = plt.subplots(2, 2, figsize=(16, 12))
    fig.suptitle('Custom CNN - Comprehensive Error Analysis', fontsize=16, fontweight='bold')

    axes[0, 0].hist(errors, bins=25, color='#e74c3c', alpha=0.7, edgecolor='black')
    axes[0, 0].set_title('Error Distribution')

    axes[0, 1].scatter(y_true, y_pred_probs.max(axis=1), alpha=0.4, color='#3498db')
    axes[0, 1].set_title('Prediction vs True Label')

    sns.boxplot(x=y_true, y=errors, ax=axes[1, 0], palette='Blues')
    axes[1, 0].set_title('Error Distribution by Class')

    cm = confusion_matrix(y_true, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[1, 1], xticklabels=class_names, yticklabels=class_names)
    axes[1, 1].set_title('Confusion Matrix (Fig 7 Style)')

    plt.tight_layout(rect=[0, 0.03, 1, 0.95]), plt.show()

plot_custom_error_analysis(model_custom, val_gen)

from sklearn.metrics import roc_curve, auc

def plot_custom_roc(model, val_gen):
    val_gen.reset()
    y_pred_probs = model.predict(val_gen)[:, 1]
    fpr, tpr, _ = roc_curve(val_gen.classes, y_pred_probs)
    roc_auc = auc(fpr, tpr)

    plt.figure(figsize=(8, 6))
    plt.plot(fpr, tpr, color='#005288', lw=2.5, label=f'AUC = {roc_auc:.3f}')
    plt.plot([0, 1], [0, 1], color='#d35400', linestyle='--', label='Random')
    plt.title('Custom CNN - ROC Curve', fontweight='bold')
    plt.legend(loc="lower right"), plt.grid(True, alpha=0.2), plt.show()

plot_custom_roc(model_custom, val_gen)

